services:
  postgres:
    container_name: ecom_postgres_db
    image: postgres:14
    environment:
      POSTGRES_USER: ecomapp
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ecom-network
    restart: unless-stopped

  mongodb:
    container_name: ecom_mongo_db
    image: mongo:noble
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ecomapp
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - ecom-network

  mongo-express:
    container_name: ecom_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: ecomapp
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    networks:
      - ecom-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ecom_kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      # --- KRaft-specific configuration ---
      # A unique ID for this Kafka node.
      KAFKA_NODE_ID: 1
      # A unique ID for the cluster. Generate this once with `kafka-storage random-uuid`.
      CLUSTER_ID: 'PhJplna4RQy0NBW5TtMVnQ'
      # Defines the roles of this node (broker and controller).
      KAFKA_PROCESS_ROLES: 'broker,controller'
      # Lists the controller nodes. For a single node, it's just itself.
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      # The listener used by controllers.
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      # --- Listener configuration (for clients) ---
      # Defines how clients connect from inside and outside Docker.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      # The address other brokers use to connect.
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      # The address external clients (on your machine) use to connect.
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'

      # --- Storage configuration ---
      # No Zookeeper, so these internal topics need a replication factor of 1.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - ecom-network

  mail-dev:
    container_name: ecom_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  zipkin:
    container_name: ecom_zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge

volumes:
  postgres_data:
  mongo:
  kafka_data: