spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: ecomapp
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8094

application:
  config:
    customer-url: http://locahost:8222/api/v1/customers
    payment-url: http://locahost:8222/api/v1/payments
    product-url: http://locahost:8222/api/v1/products

